spring.application.name=taskmanager

# Respect proxy headers from Railway
server.forward-headers-strategy=framework

# Enable Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
